---
title: "Untitled"
author: "Luis Damiano"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = TRUE, warning = TRUE)
knitr::opts_knit$set(root.dir = "..")
```

```{r preamble}
library(data.table)
library(ggplot2)
library(lme4)
library(emmeans)

for (f in dir(file.path(c("..", "."), "R"), "*.R", full.names = TRUE))
  source(f)
```

```{r initialize}
# emm_options(rg.limit = 447440, pbkrtest.limit = 154195, lmerTest.limit = 154195)
emm_options(rg.limit = 37440)
init_viz()
```

```{r read-data}
## Latest version:
## https://lumosql.org/dist/benchmarks-to-date/all-lumosql-benchmark-data-combined.sqlite
dbName   <- file.path("data-raw", "all-lumosql-benchmark-data-combined.sqlite")
benchDF0 <- get_dataframe(dbName)

## BDB uses a custom SQLite, we call this version as {versionId}bdb
benchDF0[sqliteVersion == "", 
        sqliteVersion := sprintf("%sbdb", tstrsplit(sqliteName, " ")[[1]])]

## Label run ids with zero-length backend version as "unmodified" (gabby_bch)
benchDF0[
  is.na(backendVersion), 
  `:=`(backendName =  "unmodified", backendVersion =  "unmodified")]

## Add d,d for optionDatasizes with no comma, e.g., from 3 to 3,3
benchDF0[
  !grepl(",", optionDatasize),
  optionDatasize := sprintf("%s,%s", optionDatasize, optionDatasize)]

# Break optionDatasize in optionDatasizeRead,optionDatasizeWrite
benchDF0[,
  c("optionDatasizeRead", "optionDatasizeWrite") := 
    tstrsplit(optionDatasize, ",")]

# Keep unmodified or lmdb, sqlite versions 3.34 to 3.38 (Labhraich)
benchDF1 <- benchDF0[
  backendName %like% "unmodified|lmdb" & 
    sqliteVersion %like% "3\\.3[4-8]" &
    optionDatasize %in% c("1,10", "10,1", "1,100", "3,3", "5,5", "1,5", "5,1", 
                          "1,2", "2,1", "4,4", "2,2", "1,1") &
    diskComment %in% c("ATA 256GB SATA SSD 2PE0", "ATA WDC WD10JFCX-68N 0A82", 
                       "disk/SSD ATA SanDisk SDSSDHII 00RL",
                       "hdd", "Hitachi SATA 7200RPM", "MMC/SD", "nvme", 
                       "NVME SSD SAMSUNG MZVLW256HEHP-000L7__1",
                       "ramdisk", "SAMSUNG MZVLW256HEHP-000L7__1 (NVME SSD)", 
                       "ssd", "SSD")]

benchDF  <- droplevels(benchDF1)
```

```{r replications}
repBy  <- c("optionDatasize", "backendVersion", "sqliteVersion", "diskComment", 
            "cpuComment", "osVersion")
repTab <- benchDF[, .N, by = repBy][order(-N)]
repLs  <- lapply(benchDF[, ..repBy], table)

## Main goal: compare unmodified sqlite vs lmdb
```

```{r fit-model}



## Since SQLversion is nested within backendName, 
##   consider dropping backendName in the model
fit <- lmer(log(benchRealTime) ~
              optionDatasize +                      ## Control, main interest
              backendVersion +                      ## Control, main interest
              sqliteVersion +                       ## Control, main interest
              diskComment +                         ## Envr, but large impact
              (1|cpuComment) +                      ## Blocking
              (1|osVersion),                        ## Blocking
              data = benchDF[test_number == 1])
```

```{r diagnose-model}
# Residuals ~ fitted
# Residuals ~ per input (box plot)
# Residual autocorrelation over sqlite version
```

```{r compute-emmeans}
emmBy <- c("optionDatasize", "backendVersion",
            "sqliteVersion","diskComment")

## Mean runtime per optionDatasize, backendVersion, sqliteVersion, and disk
len0 <- prod(benchDF[, lapply(.SD, uniqueN), .SDcols = emmBy])
emm0 <- emmeans(fit, ~ 1, type = "response", by = emmBy)
mDT0 <- setDT(as.data.frame(emm0))

## Mean runtime per optionDatasize, backendVersion, sqliteVersion
## for an average disk
len1 <- prod(benchDF[, lapply(.SD, uniqueN), .SDcols = emmBy[1:3]])
emm1 <- emmeans(fit, ~ 1, type = "response", by = emmBy[1:3])
mDT1 <- setDT(as.data.frame(emm1))

# tmp1 <- ref_grid(fit, ~optionDatasize)
# emmip(fit, type ~ optionDatasize | optionDatasize)
```

### Model

Add model description

### Results

```{r}
ggplot(mDT0, aes(x = optionDatasize, y = response, color = diskComment, shape = diskComment)) +
  geom_line(lwd = 0.1) +
  geom_point() +
  scale_y_log10() +
  facet_grid(sqliteVersion ~ backendVersion)
```

```{r}
mDT1L <- melt(mDT1, id.vars = c("optionDatasize"), measure.vars = "response")

ggplot(mDT1, aes(x = optionDatasize, y = response)) +
  geom_line(lwd = 0.1) +
  geom_point() +
  scale_y_log10() +
  facet_grid(sqliteVersion ~ backendVersion)
```


### Notes

#### Disk read and write time

`diskReadTime` and `diskWriteTime` are correlated with `diskComment`, 
no need to have the times in the model.

```{r results = 'hold'}
ggplot(benchDF, aes(y = diskComment, x = diskReadTime)) + 
    geom_violin() + 
    scale_x_log10()

ggplot(benchDF, aes(y = diskComment, x = diskWriteTime)) + 
    geom_violin() + 
    scale_x_log10()
```

#### CPU type and comment

```{r}
with(benchDF, table(cpuComment, cpuType))
```
